apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: apps/k3s
    repoURL: https://gitlab.sikalabs.com/examples/meriis/argocd-apps-meriis-example.git
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
